version: '3'
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=eostokens
      - POSTGRES_PASSWORD=eostokens
      - POSTGRES_DB=eostokens
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    image: avral/eostokens-api
    environment:
      - DB_HOST=db
    ports:
      - 127.0.0.1:7002:8000
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  db_upgrade:
    image: avral/eostokens-api
    environment:
      - DB_HOST=db
    command: bash -c "python manage.py createcachetable && python manage.py migrate"
