# Generated by Django 2.2.6 on 2019-11-17 05:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import history_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, null=True)),
                ('quote', models.CharField(max_length=300, null=True)),
                ('base', models.CharField(max_length=300, null=True)),
                ('bid', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Currency Amount')),
                ('ask', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Currency Amount')),
                ('price', models.IntegerField(default=0, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('order_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.IntegerField(default=0, null=True)),
                ('quote', django.contrib.postgres.fields.jsonb.JSONField(default=history_api.models.default_asset, max_length=500)),
                ('base', django.contrib.postgres.fields.jsonb.JSONField(default=history_api.models.default_asset, max_length=500)),
                ('contract', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, null=True)),
                ('quote', models.CharField(max_length=300, null=True)),
                ('base', models.CharField(max_length=300, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, null=True)),
                ('quote', models.CharField(max_length=300, null=True)),
                ('base', models.CharField(max_length=300, null=True)),
                ('bid', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Currency Amount')),
                ('ask', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Currency Amount')),
                ('price', models.IntegerField(default=0, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('order_id', models.IntegerField(null=True)),
            ],
        ),
    ]
