# Generated by Django 2.2.6 on 2019-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='base',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='market',
            name='quote',
            field=models.CharField(max_length=12),
        ),
    ]
